"""
Shared contracts for inter-service communication.

This package defines:
- Event schemas (events.py)
- Object schemas (objects.py)
- Service protocols/interfaces (protocols.py)

All services must use these contracts for communication.
Contract changes require explicit coordination and versioning.
"""

from shared.contracts.events import (
    AttentionBucket,
    AttentionCandidate,
    AttentionScoringComputedEvent,
    ArtifactRecordedEvent,
    ArtifactType,
    BaseEvent,
    DecisionRecordedEvent,
    EventType,
    FeatureSnapshotRecordedEvent,
    LabControlChangedEvent,
    LabExperimentAppliedEvent,
    LabExperimentRunEvent,
    FeedbackEvidenceRecordedEvent,
    LearningTarget,
    MessageIngestedEvent,
    ModelScoreRecordedEvent,
    ObjectExtractedEvent,
    ReminderDismissedEvent,
    ReminderSentEvent,
    ReminderSnoozedEvent,
    SourceType,
    SuggestionAppliedEvent,
    SuggestionEditedEvent,
    SuggestionRejectedEvent,
    SuggestionShownEvent,
)
from shared.contracts.lab import (
    LabConfigSnapshot,
    LabControlUpdateRequest,
    LabControlUpdateResponse,
    LabDiagnosticMetric,
    LabDiagnostics,
    LabExperimentApplyRequest,
    LabExperimentHistoryItem,
    LabExperimentHistoryResponse,
    LabExperimentRunRequest,
    LabExperimentRunResult,
    LabOverviewResponse,
    LabPersonalizationMode,
    LabRollbackRequest,
)
from shared.contracts.objects import (
    ExtractedObject,
    ExtractionResult,
    LLMServiceError,
    Note,
    ObjectType,
    Todo,
    TodoPriority,
    TodoStatus,
    Track,
    TrackStatus,
)
from shared.contracts.protocols import (
    EventStoreProtocol,
    ExtractionServiceProtocol,
    LLMServiceProtocol,
    QueryServiceProtocol,
)
from shared.contracts.tasks import (
    SuggestionType,
    TASK_LABEL_NEEDS_REVIEW,
    Task,
    TaskApplySuggestionRequest,
    TaskExplanation,
    TaskIngestRequest,
    TaskIngestResult,
    TaskLinkRequest,
    TaskPatchRequest,
    TaskPriority,
    TaskRejectSuggestionRequest,
    TaskSnoozeRequest,
    TaskSuggestion,
    TaskStatus,
)
from shared.contracts.control_room import ControlRoomOverview, ReadinessCheck, ReadinessPayload
from shared.contracts.explorer import (
    ExplorerEvidenceRef,
    ExplorerGuidedInsightsResponse,
    ExplorerMode,
    ExplorerNotableEvent,
    ExplorerPulse,
    ExplorerPulseMetric,
    ExplorerRankingFactor,
    ExplorerRankingMetadata,
    NotableSeverity,
    ExplorerDecisionEvidenceResponse,
    ExplorerDeepLinkContext,
    ExplorerEntityType,
    ExplorerIdentifierRef,
    ExplorerLookupResponse,
    ExplorerStateSnapshotResponse,
    ExplorerTimelineEvent,
    ExplorerTimelineResponse,
    ExplorerViewMode,
)

__all__ = [
    # Events
    "BaseEvent",
    "EventType",
    "AttentionBucket",
    "AttentionCandidate",
    "SourceType",
    "ArtifactType",
    "MessageIngestedEvent",
    "ArtifactRecordedEvent",
    "ObjectExtractedEvent",
    "DecisionRecordedEvent",
    "AttentionScoringComputedEvent",
    "SuggestionShownEvent",
    "SuggestionAppliedEvent",
    "SuggestionRejectedEvent",
    "SuggestionEditedEvent",
    "ReminderSentEvent",
    "ReminderDismissedEvent",
    "ReminderSnoozedEvent",
    "FeatureSnapshotRecordedEvent",
    "LabControlChangedEvent",
    "LabExperimentRunEvent",
    "LabExperimentAppliedEvent",
    "FeedbackEvidenceRecordedEvent",
    "LearningTarget",
    "ModelScoreRecordedEvent",
    # Objects
    "ObjectType",
    "TodoStatus",
    "TodoPriority",
    "Todo",
    "Note",
    "TrackStatus",
    "Track",
    "ExtractedObject",
    "ExtractionResult",
    "LLMServiceError",
    # Protocols
    "EventStoreProtocol",
    "ExtractionServiceProtocol",
    "LLMServiceProtocol",
    "QueryServiceProtocol",
    # Tasks (M5)
    "TASK_LABEL_NEEDS_REVIEW",
    "SuggestionType",
    "TaskStatus",
    "TaskPriority",
    "TaskExplanation",
    "Task",
    "TaskIngestRequest",
    "TaskIngestResult",
    "TaskPatchRequest",
    "TaskSnoozeRequest",
    "TaskLinkRequest",
    "TaskSuggestion",
    "TaskApplySuggestionRequest",
    "TaskRejectSuggestionRequest",
    # Control Room (M9)
    "ReadinessCheck",
    "ReadinessPayload",
    "ControlRoomOverview",
    # Data Explorer (M10)
    "ExplorerEntityType",
    "ExplorerMode",
    "ExplorerViewMode",
    "ExplorerIdentifierRef",
    "ExplorerLookupResponse",
    "ExplorerTimelineEvent",
    "ExplorerTimelineResponse",
    "ExplorerStateSnapshotResponse",
    "ExplorerDecisionEvidenceResponse",
    "ExplorerPulseMetric",
    "ExplorerPulse",
    "NotableSeverity",
    "ExplorerRankingFactor",
    "ExplorerRankingMetadata",
    "ExplorerEvidenceRef",
    "ExplorerNotableEvent",
    "ExplorerGuidedInsightsResponse",
    "ExplorerDeepLinkContext",
    # Lab (M11)
    "LabPersonalizationMode",
    "LabDiagnosticMetric",
    "LabDiagnostics",
    "LabConfigSnapshot",
    "LabOverviewResponse",
    "LabControlUpdateRequest",
    "LabControlUpdateResponse",
    "LabRollbackRequest",
    "LabExperimentRunRequest",
    "LabExperimentRunResult",
    "LabExperimentApplyRequest",
    "LabExperimentHistoryItem",
    "LabExperimentHistoryResponse",
]
